# Generated by Django 5.2 on 2025-05-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obra',
            old_name='endereco',
            new_name='rua',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='obra',
            name='responsavel',
        ),
        migrations.AddField(
            model_name='obra',
            name='bairro',
            field=models.CharField(default='Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='cidade',
            field=models.CharField(default='Centro', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='obra',
            name='numero',
            field=models.CharField(default='Centro', max_length=10),
            preserve_default=False,
        ),
    ]
