# Generated by Django 5.2.1 on 2025-06-28 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamento', '0002_alojamento_bairro_alojamento_cidade_and_more'),
        ('obras', '0001_initial'),
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('cancelada', 'Cancelada')], default='pendente', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True)),
                ('distancia_total', models.FloatField(blank=True, help_text='Distância em km', null=True)),
                ('tempo_estimado', models.IntegerField(blank=True, help_text='Tempo em minutos', null=True)),
                ('obra_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='obras.obra')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veiculos.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='AlojamentoOrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_parada', models.IntegerField(help_text='Ordem da parada na rota')),
                ('alojamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alojamento.alojamento')),
                ('ordem_servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alojamentos_paradas', to='ordens_servico.ordemservico')),
            ],
            options={
                'ordering': ['ordem_parada'],
                'unique_together': {('ordem_servico', 'ordem_parada')},
            },
        ),
    ]
