# Generated by Django 5.2.1 on 2025-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude da obra', null=True),
        ),
        migrations.AddField(
            model_name='obra',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude da obra', null=True),
        ),
    ]
