# Generated by Django 5.2.1 on 2025-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude do veículo', null=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude do veículo', null=True),
        ),
    ]
