# Generated by Django 5.2.1 on 2025-05-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
