# Generated by Django 5.2 on 2025-06-17 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0002_alojamento_bairro_alojamento_cidade_and_more'),
        ('funcionarios', '0002_funcionario_alojamento_funcionario_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcionario',
            options={'verbose_name': 'Funcionário', 'verbose_name_plural': 'Funcionários'},
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='rua',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='alojamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funcionarios', to='alojamento.alojamento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=100, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='É administrador?'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome_completo',
            field=models.CharField(max_length=255, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='senha',
            field=models.CharField(max_length=128, verbose_name='Senha (criptografada)'),
        ),
    ]
