# Generated by Django 5.2.1 on 2025-06-28 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_funcionario_is_admin'),
        ('funcionarios', '0003_alter_funcionario_options_remove_funcionario_bairro_and_more'),
    ]

    operations = [
    ]
