# Generated by Django 5.2.1 on 2025-06-28 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_merge_20250628_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='É administrador?'),
        ),
    ]
