# Generated by Django 5.2 on 2025-05-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('carro', 'Carro'), ('van', 'Van'), ('caminhao', 'Caminhão'), ('moto', 'Moto')], max_length=20)),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('capacidade', models.PositiveIntegerField()),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('disponibilidade', models.BooleanField(default=True)),
            ],
        ),
    ]
