# Generated by Django 5.2 on 2025-06-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamento',
            name='bairro',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='alojamento',
            name='cidade',
            field=models.CharField(default='Desconhecido', max_length=100),
        ),
        migrations.AddField(
            model_name='alojamento',
            name='numero',
            field=models.CharField(default='S/N', max_length=10),
        ),
        migrations.AddField(
            model_name='alojamento',
            name='rua',
            field=models.CharField(default='Desconhecida', max_length=255),
        ),
    ]
