# Generated by Django 5.2.1 on 2025-06-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamento', '0002_alojamento_bairro_alojamento_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alojamento',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude do alojamento', null=True),
        ),
        migrations.AddField(
            model_name='alojamento',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude do alojamento', null=True),
        ),
    ]
