# Generated by Django 5.2 on 2025-05-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
